name: Create pull request

on:   
  pull_request:
    branches:
      - main

env:
  GH_TOKEN: ${{ github.TOKEN }}

jobs:
  build-info-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Build info
        run: |
          echo "Dispatch workflow"
          echo "GH_TOKEN: ${{ env.GH_TOKEN }}"
          echo "head: ${{ github.ref_name }}"
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}


  create-pull-request:
    permissions:
      pull-requests: write
      security-events: write
    runs-on: ubuntu-20.04
    steps:
      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: '[Example] Simple demo',
              owner,
              repo,
              head: 'test-pr',
              base: 'test-create-pr-manual',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['feature', 'automated pr']
            });
