name: Create pull request

on: workflow_dispatch

env:
  GH_TOKEN: ${{ github.TOKEN }}

jobs:
  build-info-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Build info
        run: |
          echo "Dispatch workflow"
          echo "GH_TOKEN: ${{ env.GH_TOKEN }}"
