name: test-dispatch-2

on: 
  pull_request:
    branches:    
      - 'integration/**'

# env:
#   TEST_SECRET: ${{ secrets.TEST_SECRET }}
#   GH_TOKEN: ${{ secrets.TEST_GH_TOKEN }}
  
jobs:
  build-info-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Build info
        run: |
          echo "Integration workflow"
