name: integration test

on: pull_request

# env:
#   TEST_SECRET: ${{ secrets.TEST_SECRET }}
#   GH_TOKEN: ${{ secrets.TEST_GH_TOKEN }}
  
jobs:
  validate:
    if: startsWith(github.head_ref, 'integration/')
    runs-on: ubuntu-latest  
    steps:
      - run: echo "Validate..."


