name: test-pull_request

on:
  pull_request:
    branches:
      - main

env:
  TEST_SECRET: ${{ secrets.TEST_SECRET }}

jobs:
  build-info-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Build info
        run: |
          echo "Pull request workflow"
          echo "TEST_SECRET: ${{ env.TEST_SECRET }}"
