name: test-dispatch-2

on: workflow_dispatch

env:
  TEST_SECRET: ${{ secrets.TEST_SECRET }}
  GH_TOKEN: ${{ secrets.TEST_GH_TOKEN }}
  
jobs:
  build-info-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Build info
        run: |
          echo "Dispatch manual workflow"
          echo "TEST_SECRET: ${{ env.TEST_SECRET }}"
          echo "GH_TOKEN: ${{ env.GH_TOKEN }}"
