name: test-dispatch

on: workflow_dispatch

env:
  TEST_SECRET: ${{ secrets.TEST_SECRET }}

jobs:
  build-info-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Build info
        run: |
          echo "Dispatch workflow"
          echo "TEST_SECRET: ${{ env.TEST_SECRET }}"
